apiVersion: apps/v1
kind: Deployment
metadata:
  name: doggo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doggo
  template:
    metadata:
      labels:
        app: doggo
    spec:
      containers:
      - name: doggo
        image: ghcr.io/k-avy/doggo:main
